// English TheMealDB ingredient name → German DEFAULT_INGREDIENTS entry
// (or new ingredient with deutsch name + icon)
//
// Format: { name: "Deutscher Name", icon: "🍅" }
// The German names should match DEFAULT_INGREDIENTS where possible.

export const INGREDIENT_MAP = {
  // ── Vegetables / Gemüse ──
  "Onion": { name: "Zwiebel", icon: "🧅" },
  "Onions": { name: "Zwiebel", icon: "🧅" },
  "Red Onion": { name: "Rote Zwiebel", icon: "🧅" },
  "Red Onions": { name: "Rote Zwiebel", icon: "🧅" },
  "White Onion": { name: "Zwiebel", icon: "🧅" },
  "Yellow Onion": { name: "Zwiebel", icon: "🧅" },
  "Spring Onions": { name: "Frühlingszwiebel", icon: "🧅" },
  "Spring Onion": { name: "Frühlingszwiebel", icon: "🧅" },
  "Garlic": { name: "Knoblauch", icon: "🧄" },
  "Garlic Clove": { name: "Knoblauch", icon: "🧄" },
  "Garlic Cloves": { name: "Knoblauch", icon: "🧄" },
  "Garlic Powder": { name: "Knoblauchpulver", icon: "🧄" },
  "Tomato": { name: "Tomate", icon: "🍅" },
  "Tomatoes": { name: "Tomate", icon: "🍅" },
  "Cherry Tomatoes": { name: "Tomate", icon: "🍅" },
  "Plum Tomatoes": { name: "Tomate", icon: "🍅" },
  "Tomato Puree": { name: "Tomatenmark", icon: "🥫" },
  "Tomato Paste": { name: "Tomatenmark", icon: "🥫" },
  "Chopped Tomatoes": { name: "Passierte Tomaten", icon: "🥫" },
  "Tinned Tomatos": { name: "Passierte Tomaten", icon: "🥫" },
  "Carrots": { name: "Karotte", icon: "🥕" },
  "Carrot": { name: "Karotte", icon: "🥕" },
  "Potatoes": { name: "Kartoffel", icon: "🥔" },
  "Potato": { name: "Kartoffel", icon: "🥔" },
  "Sweet Potatoes": { name: "Süßkartoffel", icon: "🥔" },
  "Sweet Potato": { name: "Süßkartoffel", icon: "🥔" },
  "Cucumber": { name: "Gurke", icon: "🥒" },
  "Zucchini": { name: "Zucchini", icon: "🥒" },
  "Courgette": { name: "Zucchini", icon: "🥒" },
  "Courgettes": { name: "Zucchini", icon: "🥒" },
  "Aubergine": { name: "Aubergine", icon: "🍆" },
  "Eggplant": { name: "Aubergine", icon: "🍆" },
  "Bell Pepper": { name: "Paprika", icon: "🫑" },
  "Red Pepper": { name: "Paprika (rot)", icon: "🫑" },
  "Green Pepper": { name: "Paprika (grün)", icon: "🫑" },
  "Yellow Pepper": { name: "Paprika (gelb)", icon: "🫑" },
  "Romano Pepper": { name: "Spitzpaprika", icon: "🫑" },
  "Red Pepper Paste": { name: "Paprikapaste", icon: "🥫" },
  "Pepper Paste": { name: "Paprikapaste", icon: "🥫" },
  "Red Chilli": { name: "Chili", icon: "🌶️" },
  "Green Chilli": { name: "Chili", icon: "🌶️" },
  "Chilli": { name: "Chili", icon: "🌶️" },
  "Chili": { name: "Chili", icon: "🌶️" },
  "Chilli Powder": { name: "Chilipulver", icon: "🌶️" },
  "Broccoli": { name: "Brokkoli", icon: "🥦" },
  "Cauliflower": { name: "Blumenkohl", icon: "🥦" },
  "Spinach": { name: "Spinat", icon: "🥬" },
  "Lettuce": { name: "Salat", icon: "🥬" },
  "Mushrooms": { name: "Champignon", icon: "🍄" },
  "Mushroom": { name: "Champignon", icon: "🍄" },
  "Leek": { name: "Lauch", icon: "🥬" },
  "Leeks": { name: "Lauch", icon: "🥬" },
  "Celery": { name: "Sellerie", icon: "🥬" },
  "Pumpkin": { name: "Kürbis", icon: "🎃" },
  "Butternut Squash": { name: "Kürbis", icon: "🎃" },
  "Peas": { name: "Erbsen", icon: "🫛" },
  "Frozen Peas": { name: "Erbsen", icon: "🫛" },
  "Green Beans": { name: "Bohnen (grün)", icon: "🫛" },
  "Ginger": { name: "Ingwer", icon: "🫚" },
  "Fresh Ginger": { name: "Ingwer", icon: "🫚" },
  "Beetroot": { name: "Rote Bete", icon: "🥕" },
  "Fennel": { name: "Fenchel", icon: "🥬" },
  "Radishes": { name: "Radieschen", icon: "🥕" },
  "Asparagus": { name: "Spargel", icon: "🥬" },
  "Olives": { name: "Oliven", icon: "🫒" },
  "Black Olives": { name: "Oliven", icon: "🫒" },
  "Avocado": { name: "Avocado", icon: "🥑" },
  "Cabbage": { name: "Weißkohl", icon: "🥬" },
  "Red Cabbage": { name: "Rotkohl", icon: "🥬" },
  "Kohlrabi": { name: "Kohlrabi", icon: "🥬" },
  "Sweetcorn": { name: "Mais", icon: "🌽" },
  "Corn": { name: "Mais", icon: "🌽" },
  "Shallot": { name: "Schalotte", icon: "🧅" },
  "Shallots": { name: "Schalotte", icon: "🧅" },

  // ── Fruit / Obst ──
  "Apple": { name: "Apfel", icon: "🍎" },
  "Apples": { name: "Apfel", icon: "🍎" },
  "Banana": { name: "Banane", icon: "🍌" },
  "Bananas": { name: "Banane", icon: "🍌" },
  "Lemon": { name: "Zitrone", icon: "🍋" },
  "Lemons": { name: "Zitrone", icon: "🍋" },
  "Lemon Juice": { name: "Zitronensaft", icon: "🍋" },
  "Lemon Zest": { name: "Zitronenschale", icon: "🍋" },
  "Lime": { name: "Limette", icon: "🍋" },
  "Limes": { name: "Limette", icon: "🍋" },
  "Lime Juice": { name: "Limettensaft", icon: "🍋" },
  "Orange": { name: "Orange", icon: "🍊" },
  "Oranges": { name: "Orange", icon: "🍊" },
  "Orange Juice": { name: "Orangensaft", icon: "🍊" },
  "Strawberries": { name: "Erdbeere", icon: "🍓" },
  "Blueberries": { name: "Blaubeere", icon: "🫐" },
  "Raspberries": { name: "Himbeere", icon: "🍓" },
  "Grapes": { name: "Weintraube", icon: "🍇" },
  "Peaches": { name: "Pfirsich", icon: "🍑" },
  "Pears": { name: "Birne", icon: "🍐" },
  "Mango": { name: "Mango", icon: "🥭" },
  "Pineapple": { name: "Ananas", icon: "🍍" },
  "Cherries": { name: "Kirsche", icon: "🍒" },
  "Watermelon": { name: "Wassermelone", icon: "🍉" },
  "Kiwi": { name: "Kiwi", icon: "🥝" },
  "Coconut": { name: "Kokosnuss", icon: "🥥" },
  "Coconut Milk": { name: "Kokosmilch", icon: "🥥" },
  "Coconut Cream": { name: "Kokosmilch", icon: "🥥" },
  "Plums": { name: "Pflaume", icon: "🍑" },
  "Raisins": { name: "Rosinen", icon: "🍇" },
  "Sultanas": { name: "Rosinen", icon: "🍇" },

  // ── Meat / Fleisch ──
  "Chicken": { name: "Hähnchen", icon: "🍗" },
  "Chicken Breast": { name: "Hähnchenbrust", icon: "🍗" },
  "Chicken Breasts": { name: "Hähnchenbrust", icon: "🍗" },
  "Boneless Chicken Breast": { name: "Hähnchenbrust", icon: "🍗" },
  "Chicken Thighs": { name: "Hähnchenschenkel", icon: "🍗" },
  "Chicken Legs": { name: "Hähnchenschenkel", icon: "🍗" },
  "Chicken Drumsticks": { name: "Hähnchenschenkel", icon: "🍗" },
  "Chicken Wings": { name: "Hähnchenflügel", icon: "🍗" },
  "Chicken Stock": { name: "Brühe (Hühner)", icon: "🍲" },
  "Chicken Stock Cube": { name: "Brühe (Hühner)", icon: "🍲" },
  "Chicken Bouillon Powder": { name: "Brühe (Hühner)", icon: "🍲" },
  "Beef": { name: "Rindfleisch", icon: "🥩" },
  "Ground Beef": { name: "Hackfleisch (Rind)", icon: "🥩" },
  "Beef Mince": { name: "Hackfleisch (Rind)", icon: "🥩" },
  "Minced Beef": { name: "Hackfleisch (Rind)", icon: "🥩" },
  "Beef Stock": { name: "Brühe (Rinder)", icon: "🍲" },
  "Beef Brisket": { name: "Rinderbrust", icon: "🥩" },
  "Beef Steak": { name: "Rindersteak", icon: "🥩" },
  "Steak": { name: "Steak", icon: "🥩" },
  "Pork": { name: "Schweinefleisch", icon: "🥩" },
  "Pork Mince": { name: "Hackfleisch (Schwein)", icon: "🥩" },
  "Ground Pork": { name: "Hackfleisch (Schwein)", icon: "🥩" },
  "Pork Belly": { name: "Schweinebauch", icon: "🥩" },
  "Pork Chops": { name: "Schweinekotelett", icon: "🥩" },
  "Pork Loin": { name: "Schweinelende", icon: "🥩" },
  "Bacon": { name: "Speck", icon: "🥓" },
  "Bacon Lardons": { name: "Speck", icon: "🥓" },
  "Streaky Bacon": { name: "Speck", icon: "🥓" },
  "Pancetta": { name: "Pancetta", icon: "🥓" },
  "Ham": { name: "Schinken", icon: "🥓" },
  "Salami": { name: "Salami", icon: "🌭" },
  "Sausages": { name: "Würstchen", icon: "🌭" },
  "Sausage": { name: "Würstchen", icon: "🌭" },
  "Chorizo": { name: "Chorizo", icon: "🌭" },
  "Lamb": { name: "Lammfleisch", icon: "🥩" },
  "Lamb Mince": { name: "Hackfleisch (Lamm)", icon: "🥩" },
  "Lamb Shoulder": { name: "Lammschulter", icon: "🥩" },
  "Lamb Leg": { name: "Lammkeule", icon: "🥩" },
  "Turkey": { name: "Putenbrust", icon: "🍗" },
  "Duck": { name: "Entenbrust", icon: "🍗" },
  "Duck Breast": { name: "Entenbrust", icon: "🍗" },

  // ── Fish / Fisch ──
  "Salmon": { name: "Lachs", icon: "🐟" },
  "Tuna": { name: "Thunfisch", icon: "🐟" },
  "Cod": { name: "Kabeljau", icon: "🐟" },
  "Trout": { name: "Forelle", icon: "🐟" },
  "Prawns": { name: "Garnelen", icon: "🦐" },
  "Shrimp": { name: "Garnelen", icon: "🦐" },
  "King Prawns": { name: "Garnelen", icon: "🦐" },
  "Mussels": { name: "Muscheln", icon: "🦀" },
  "Squid": { name: "Tintenfisch", icon: "🦑" },
  "Anchovies": { name: "Sardellen", icon: "🐟" },
  "Anchovy Fillet": { name: "Sardellen", icon: "🐟" },
  "Sardines": { name: "Sardinen", icon: "🐟" },
  "Mackerel": { name: "Makrele", icon: "🐟" },
  "Haddock": { name: "Schellfisch", icon: "🐟" },
  "Sea Bass": { name: "Wolfsbarsch", icon: "🐟" },
  "Tilapia": { name: "Tilapia", icon: "🐟" },
  "White Fish": { name: "Weißfisch", icon: "🐟" },

  // ── Dairy / Milchprodukte ──
  "Milk": { name: "Milch", icon: "🥛" },
  "Whole Milk": { name: "Milch", icon: "🥛" },
  "Semi-skimmed Milk": { name: "Milch", icon: "🥛" },
  "Butter": { name: "Butter", icon: "🧈" },
  "Unsalted Butter": { name: "Butter", icon: "🧈" },
  "Salted Butter": { name: "Butter", icon: "🧈" },
  "Cream": { name: "Sahne", icon: "🥛" },
  "Double Cream": { name: "Sahne", icon: "🥛" },
  "Single Cream": { name: "Sahne", icon: "🥛" },
  "Heavy Cream": { name: "Sahne", icon: "🥛" },
  "Whipping Cream": { name: "Sahne", icon: "🥛" },
  "Sour Cream": { name: "Sauerrahm", icon: "🥛" },
  "Crème Fraiche": { name: "Crème fraîche", icon: "🥛" },
  "Cream Cheese": { name: "Frischkäse", icon: "🧀" },
  "Mozzarella": { name: "Mozzarella", icon: "🧀" },
  "Parmesan": { name: "Parmesan", icon: "🧀" },
  "Parmesan Cheese": { name: "Parmesan", icon: "🧀" },
  "Cheddar Cheese": { name: "Cheddar", icon: "🧀" },
  "Cheddar": { name: "Cheddar", icon: "🧀" },
  "Gouda": { name: "Gouda", icon: "🧀" },
  "Gouda Cheese": { name: "Gouda", icon: "🧀" },
  "Feta": { name: "Feta", icon: "🧀" },
  "Feta Cheese": { name: "Feta", icon: "🧀" },
  "Goat Cheese": { name: "Ziegenkäse", icon: "🧀" },
  "Cheese": { name: "Käse (gerieben)", icon: "🧀" },
  "Yogurt": { name: "Joghurt", icon: "🥛" },
  "Yoghurt": { name: "Joghurt", icon: "🥛" },
  "Greek Yogurt": { name: "Griechischer Joghurt", icon: "🥛" },
  "Greek Yoghurt": { name: "Griechischer Joghurt", icon: "🥛" },
  "Quark": { name: "Quark", icon: "🥛" },
  "Mascarpone": { name: "Mascarpone", icon: "🧀" },
  "Ricotta": { name: "Ricotta", icon: "🧀" },
  "Buttermilk": { name: "Buttermilch", icon: "🥛" },
  "Condensed Milk": { name: "Kondensmilch", icon: "🥛" },
  "Evaporated Milk": { name: "Kondensmilch", icon: "🥛" },

  // ── Grains / Getreide ──
  "Flour": { name: "Mehl", icon: "🌾" },
  "Plain Flour": { name: "Mehl", icon: "🌾" },
  "All purpose flour": { name: "Mehl", icon: "🌾" },
  "All-Purpose Flour": { name: "Mehl", icon: "🌾" },
  "Self-raising Flour": { name: "Mehl mit Backpulver", icon: "🌾" },
  "Bread Flour": { name: "Brotmehl", icon: "🌾" },
  "Strong Bread Flour": { name: "Brotmehl", icon: "🌾" },
  "Wholemeal Flour": { name: "Vollkornmehl", icon: "🌾" },
  "Rice": { name: "Reis", icon: "🍚" },
  "Basmati Rice": { name: "Basmatireis", icon: "🍚" },
  "Long Grain Rice": { name: "Langkornreis", icon: "🍚" },
  "Arborio Rice": { name: "Risotto-Reis", icon: "🍚" },
  "Pasta": { name: "Pasta (Spaghetti)", icon: "🍝" },
  "Spaghetti": { name: "Pasta (Spaghetti)", icon: "🍝" },
  "Penne": { name: "Pasta (Penne)", icon: "🍝" },
  "Fusilli": { name: "Pasta (Fusilli)", icon: "🍝" },
  "Lasagne Sheets": { name: "Lasagneplatten", icon: "🍝" },
  "Lasagne": { name: "Lasagneplatten", icon: "🍝" },
  "Macaroni": { name: "Pasta (Penne)", icon: "🍝" },
  "Tagliatelle": { name: "Pasta (Spaghetti)", icon: "🍝" },
  "Linguine": { name: "Pasta (Spaghetti)", icon: "🍝" },
  "Fettuccine": { name: "Pasta (Spaghetti)", icon: "🍝" },
  "Noodles": { name: "Nudeln", icon: "🍜" },
  "Rice Noodles": { name: "Reisnudeln", icon: "🍜" },
  "Egg Noodles": { name: "Nudeln", icon: "🍜" },
  "Bread": { name: "Brot", icon: "🍞" },
  "White Bread": { name: "Brot", icon: "🍞" },
  "Bread Crumbs": { name: "Paniermehl", icon: "🌾" },
  "Breadcrumbs": { name: "Paniermehl", icon: "🌾" },
  "Panko": { name: "Panko", icon: "🌾" },
  "Tortilla": { name: "Tortilla", icon: "🫓" },
  "Tortillas": { name: "Tortilla", icon: "🫓" },
  "Puff Pastry": { name: "Blätterteig", icon: "🥐" },
  "Filo Pastry": { name: "Blätterteig", icon: "🥐" },
  "Pizza Dough": { name: "Pizzateig", icon: "🫓" },
  "Oats": { name: "Haferflocken", icon: "🥣" },
  "Porridge Oats": { name: "Haferflocken", icon: "🥣" },
  "Couscous": { name: "Couscous", icon: "🍚" },
  "Bulgur Wheat": { name: "Bulgur", icon: "🍚" },
  "Quinoa": { name: "Quinoa", icon: "🍚" },
  "Polenta": { name: "Polenta", icon: "🌾" },
  "Cornmeal": { name: "Polenta", icon: "🌾" },

  // ── Spices / Gewürze ──
  "Salt": { name: "Salz", icon: "🧂" },
  "Sea Salt": { name: "Salz", icon: "🧂" },
  "Pepper": { name: "Pfeffer", icon: "🧂" },
  "Black Pepper": { name: "Pfeffer", icon: "🧂" },
  "White Pepper": { name: "Pfeffer", icon: "🧂" },
  "Paprika": { name: "Paprikapulver", icon: "🌶️" },
  "Smoked Paprika": { name: "Paprikapulver (geräuchert)", icon: "🌶️" },
  "Cumin": { name: "Kreuzkümmel (Cumin)", icon: "🧂" },
  "Ground Cumin": { name: "Kreuzkümmel (Cumin)", icon: "🧂" },
  "Cumin Seeds": { name: "Kreuzkümmel (Cumin)", icon: "🧂" },
  "Turmeric": { name: "Kurkuma", icon: "🧂" },
  "Curry Powder": { name: "Curry", icon: "🧂" },
  "Curry Paste": { name: "Currypaste", icon: "🥫" },
  "Cinnamon": { name: "Zimt", icon: "🧂" },
  "Ground Cinnamon": { name: "Zimt", icon: "🧂" },
  "Cinnamon Stick": { name: "Zimt", icon: "🧂" },
  "Nutmeg": { name: "Muskatnuss", icon: "🧂" },
  "Oregano": { name: "Oregano", icon: "🌿" },
  "Dried Oregano": { name: "Oregano", icon: "🌿" },
  "Basil": { name: "Basilikum", icon: "🌿" },
  "Fresh Basil": { name: "Basilikum", icon: "🌿" },
  "Thyme": { name: "Thymian", icon: "🌿" },
  "Fresh Thyme": { name: "Thymian", icon: "🌿" },
  "Rosemary": { name: "Rosmarin", icon: "🌿" },
  "Fresh Rosemary": { name: "Rosmarin", icon: "🌿" },
  "Parsley": { name: "Petersilie", icon: "🌿" },
  "Fresh Parsley": { name: "Petersilie", icon: "🌿" },
  "Flat Leaf Parsley": { name: "Petersilie", icon: "🌿" },
  "Chives": { name: "Schnittlauch", icon: "🌿" },
  "Dill": { name: "Dill", icon: "🌿" },
  "Mint": { name: "Minze", icon: "🍃" },
  "Fresh Mint": { name: "Minze", icon: "🍃" },
  "Coriander": { name: "Koriander", icon: "🌿" },
  "Fresh Coriander": { name: "Koriander", icon: "🌿" },
  "Cilantro": { name: "Koriander", icon: "🌿" },
  "Bay Leaf": { name: "Lorbeerblatt", icon: "🍃" },
  "Bay Leaves": { name: "Lorbeerblatt", icon: "🍃" },
  "Vanilla Extract": { name: "Vanille", icon: "🌰" },
  "Vanilla": { name: "Vanille", icon: "🌰" },
  "Vanilla Pod": { name: "Vanille", icon: "🌰" },
  "Saffron": { name: "Safran", icon: "🧂" },
  "Cardamom": { name: "Kardamom", icon: "🧂" },
  "Cardamom Pods": { name: "Kardamom", icon: "🧂" },
  "Cloves": { name: "Nelken", icon: "🧂" },
  "Star Anise": { name: "Sternanis", icon: "🧂" },
  "Allspice": { name: "Piment", icon: "🧂" },
  "Garam Masala": { name: "Garam Masala", icon: "🧂" },
  "Mustard Seeds": { name: "Senfkörner", icon: "🧂" },
  "Fennel Seeds": { name: "Fenchelsamen", icon: "🧂" },
  "Five Spice Powder": { name: "Fünf-Gewürze-Pulver", icon: "🧂" },
  "Pul Biber": { name: "Pul Biber", icon: "🌶️" },
  "Cayenne Pepper": { name: "Cayennepfeffer", icon: "🌶️" },
  "Chili Powder": { name: "Chilipulver", icon: "🌶️" },
  "Ground Ginger": { name: "Ingwer (gemahlen)", icon: "🫚" },

  // ── Oils & Fats / Öle ──
  "Olive Oil": { name: "Olivenöl", icon: "🫗" },
  "Extra Virgin Olive Oil": { name: "Olivenöl", icon: "🫗" },
  "Vegetable Oil": { name: "Pflanzenöl", icon: "🫗" },
  "Sunflower Oil": { name: "Sonnenblumenöl", icon: "🫗" },
  "Rapeseed Oil": { name: "Rapsöl", icon: "🫗" },
  "Canola Oil": { name: "Rapsöl", icon: "🫗" },
  "Sesame Oil": { name: "Sesamöl", icon: "🫗" },
  "Coconut Oil": { name: "Kokosöl", icon: "🥥" },
  "Oil": { name: "Öl", icon: "🫗" },
  "Cooking Oil": { name: "Öl", icon: "🫗" },
  "Ghee": { name: "Butterschmalz", icon: "🧈" },
  "Lard": { name: "Schweineschmalz", icon: "🧈" },

  // ── Sauces / Saucen ──
  "Soy Sauce": { name: "Sojasauce", icon: "🫗" },
  "Light Soy Sauce": { name: "Sojasauce", icon: "🫗" },
  "Dark Soy Sauce": { name: "Sojasauce", icon: "🫗" },
  "Worcestershire Sauce": { name: "Worcestersauce", icon: "🫗" },
  "Mustard": { name: "Senf", icon: "🥫" },
  "Dijon Mustard": { name: "Senf", icon: "🥫" },
  "Wholegrain Mustard": { name: "Senf", icon: "🥫" },
  "English Mustard": { name: "Senf", icon: "🥫" },
  "Ketchup": { name: "Ketchup", icon: "🥫" },
  "Tomato Ketchup": { name: "Ketchup", icon: "🥫" },
  "Mayonnaise": { name: "Mayonnaise", icon: "🥫" },
  "Vinegar": { name: "Essig", icon: "🫗" },
  "White Wine Vinegar": { name: "Weißweinessig", icon: "🫗" },
  "Red Wine Vinegar": { name: "Rotweinessig", icon: "🫗" },
  "Apple Cider Vinegar": { name: "Apfelessig", icon: "🫗" },
  "Rice Vinegar": { name: "Reisessig", icon: "🫗" },
  "Balsamic Vinegar": { name: "Balsamico", icon: "🫗" },
  "Pesto": { name: "Pesto", icon: "🥫" },
  "Tabasco": { name: "Tabasco", icon: "🌶️" },
  "Hot Sauce": { name: "Tabasco", icon: "🌶️" },
  "Sambal Oelek": { name: "Sambal Oelek", icon: "🌶️" },
  "Sriracha": { name: "Sriracha", icon: "🌶️" },
  "Tahini": { name: "Tahini", icon: "🥫" },
  "Fish Sauce": { name: "Fischsauce", icon: "🐟" },
  "Teriyaki Sauce": { name: "Teriyaki-Sauce", icon: "🫗" },
  "Hoisin Sauce": { name: "Hoisin-Sauce", icon: "🫗" },
  "Oyster Sauce": { name: "Austernsauce", icon: "🫗" },
  "Sweet Chilli Sauce": { name: "Sweet-Chili-Sauce", icon: "🌶️" },
  "Vegetable Stock": { name: "Brühe (Gemüse)", icon: "🍲" },
  "Vegetable Stock Cube": { name: "Brühe (Gemüse)", icon: "🍲" },
  "Stock": { name: "Brühe (Gemüse)", icon: "🍲" },
  "Stock Cube": { name: "Brühe (Gemüse)", icon: "🍲" },
  "Mirin": { name: "Mirin", icon: "🍶" },
  "Sake": { name: "Sake", icon: "🍶" },
  "Gochujang": { name: "Gochujang", icon: "🌶️" },

  // ── Legumes & Nuts / Hülsenfrüchte ──
  "Chickpeas": { name: "Kichererbsen", icon: "🫘" },
  "Kidney Beans": { name: "Kidneybohnen", icon: "🫘" },
  "Cannellini Beans": { name: "Weiße Bohnen", icon: "🫘" },
  "Butter Beans": { name: "Weiße Bohnen", icon: "🫘" },
  "Black Beans": { name: "Schwarze Bohnen", icon: "🫘" },
  "Red Lentils": { name: "Linsen (rot)", icon: "🫘" },
  "Lentils": { name: "Linsen (grün)", icon: "🫘" },
  "Green Lentils": { name: "Linsen (grün)", icon: "🫘" },
  "Peanuts": { name: "Erdnüsse", icon: "🥜" },
  "Almonds": { name: "Mandeln", icon: "🌰" },
  "Ground Almonds": { name: "Mandeln (gemahlen)", icon: "🌰" },
  "Flaked Almonds": { name: "Mandeln", icon: "🌰" },
  "Walnuts": { name: "Walnüsse", icon: "🌰" },
  "Cashews": { name: "Cashews", icon: "🌰" },
  "Cashew Nuts": { name: "Cashews", icon: "🌰" },
  "Pine Nuts": { name: "Pinienkerne", icon: "🌰" },
  "Sesame Seeds": { name: "Sesam", icon: "🌰" },
  "Sunflower Seeds": { name: "Sonnenblumenkerne", icon: "🌰" },
  "Peanut Butter": { name: "Erdnussbutter", icon: "🥜" },
  "Tofu": { name: "Tofu", icon: "🧆" },
  "Pistachios": { name: "Pistazien", icon: "🌰" },
  "Pecans": { name: "Pekannüsse", icon: "🌰" },
  "Hazelnuts": { name: "Haselnüsse", icon: "🌰" },
  "Macadamia Nuts": { name: "Macadamia", icon: "🌰" },

  // ── Eggs / Baking ──
  "Egg": { name: "Ei", icon: "🥚" },
  "Eggs": { name: "Ei", icon: "🥚" },
  "Egg Yolks": { name: "Eigelb", icon: "🥚" },
  "Egg Yolk": { name: "Eigelb", icon: "🥚" },
  "Egg Whites": { name: "Eiweiß", icon: "🥚" },
  "Egg White": { name: "Eiweiß", icon: "🥚" },
  "Sugar": { name: "Zucker", icon: "🧂" },
  "Caster Sugar": { name: "Zucker", icon: "🧂" },
  "Granulated Sugar": { name: "Zucker", icon: "🧂" },
  "Icing Sugar": { name: "Puderzucker", icon: "🧂" },
  "Powdered Sugar": { name: "Puderzucker", icon: "🧂" },
  "Brown Sugar": { name: "Brauner Zucker", icon: "🧂" },
  "Light Brown Sugar": { name: "Brauner Zucker", icon: "🧂" },
  "Dark Brown Sugar": { name: "Brauner Zucker", icon: "🧂" },
  "Demerara Sugar": { name: "Brauner Zucker", icon: "🧂" },
  "Honey": { name: "Honig", icon: "🍯" },
  "Maple Syrup": { name: "Ahornsirup", icon: "🍯" },
  "Golden Syrup": { name: "Ahornsirup", icon: "🍯" },
  "Treacle": { name: "Ahornsirup", icon: "🍯" },
  "Baking Powder": { name: "Backpulver", icon: "🧁" },
  "Baking Soda": { name: "Natron", icon: "🧁" },
  "Bicarbonate Of Soda": { name: "Natron", icon: "🧁" },
  "Yeast": { name: "Hefe", icon: "🧁" },
  "Dried Yeast": { name: "Hefe", icon: "🧁" },
  "Active Dry Yeast": { name: "Hefe", icon: "🧁" },
  "Cornstarch": { name: "Speisestärke", icon: "🌾" },
  "Cornflour": { name: "Speisestärke", icon: "🌾" },
  "Corn Starch": { name: "Speisestärke", icon: "🌾" },
  "Gelatine": { name: "Gelatine", icon: "🧁" },
  "Dark Chocolate": { name: "Schokolade (Zartbitter)", icon: "🍫" },
  "Plain Chocolate": { name: "Schokolade (Zartbitter)", icon: "🍫" },
  "Milk Chocolate": { name: "Schokolade (Vollmilch)", icon: "🍫" },
  "White Chocolate": { name: "Weiße Schokolade", icon: "🍫" },
  "Chocolate Chips": { name: "Schokoladentropfen", icon: "🍫" },
  "Cocoa Powder": { name: "Kakao", icon: "🍫" },
  "Cocoa": { name: "Kakao", icon: "🍫" },

  // ── Drinks ──
  "Water": { name: "Wasser", icon: "💧" },
  "Hot Water": { name: "Wasser", icon: "💧" },
  "Cold Water": { name: "Wasser", icon: "💧" },
  "White Wine": { name: "Weißwein", icon: "🍷" },
  "Red Wine": { name: "Rotwein", icon: "🍷" },
  "Wine": { name: "Wein", icon: "🍷" },
  "Beer": { name: "Bier", icon: "🍺" },
  "Apple Juice": { name: "Apfelsaft", icon: "🧃" },

  // ── Misc ──
  "Capers": { name: "Kapern", icon: "🫒" },
  "Gherkins": { name: "Cornichons", icon: "🥒" },
  "Pickles": { name: "Cornichons", icon: "🥒" },
  "Miso": { name: "Miso-Paste", icon: "🥫" },
  "Miso Paste": { name: "Miso-Paste", icon: "🥫" },
  "Nori": { name: "Nori (Seetang)", icon: "🍃" },
  "Tortilla Chips": { name: "Tortilla-Chips", icon: "🌮" },
  "Dates": { name: "Datteln", icon: "🌰" },
  "Apricots": { name: "Aprikosen", icon: "🍑" },
  "Dried Apricots": { name: "Aprikose getrocknet", icon: "🍑" },

  // ── Round 2: from first dry-run unmatched list ──
  "Scallions": { name: "Frühlingszwiebel", icon: "🧅" },
  "Creme Fraiche": { name: "Crème fraîche", icon: "🥛" },
  "Scotch Bonnet": { name: "Scotch-Bonnet-Chili", icon: "🌶️" },
  "Dry sherry": { name: "Sherry", icon: "🍷" },
  "Sherry": { name: "Sherry", icon: "🍷" },
  "Harissa Spice": { name: "Harissa", icon: "🌶️" },
  "Harissa": { name: "Harissa", icon: "🌶️" },
  "Rocket": { name: "Rucola", icon: "🥬" },
  "Arugula": { name: "Rucola", icon: "🥬" },
  "Challots": { name: "Schalotte", icon: "🧅" },
  "Bean Sprouts": { name: "Sojasprossen", icon: "🌱" },
  "Brandy": { name: "Brandy", icon: "🥃" },
  "Baguette": { name: "Baguette", icon: "🥖" },
  "Dulce de leche": { name: "Dulce de leche", icon: "🍯" },
  "Kale": { name: "Grünkohl", icon: "🥬" },
  "Shortcrust Pastry": { name: "Mürbeteig", icon: "🥐" },
  "Blackberries": { name: "Brombeeren", icon: "🫐" },
  "Almond Extract": { name: "Mandelaroma", icon: "🌰" },
  "almond extract": { name: "Mandelaroma", icon: "🌰" },
  "Swede": { name: "Steckrübe", icon: "🥕" },
  "Rutabaga": { name: "Steckrübe", icon: "🥕" },
  "Marjoram": { name: "Majoran", icon: "🌿" },
  "Molasses": { name: "Melasse", icon: "🍯" },
  "Jalapeno": { name: "Jalapeño", icon: "🌶️" },
  "Jalapeño": { name: "Jalapeño", icon: "🌶️" },
  "Dried white beans": { name: "Weiße Bohnen (getrocknet)", icon: "🫘" },
  "Tamarind Paste": { name: "Tamarindenpaste", icon: "🥫" },
  "Pecan Nuts": { name: "Pekannüsse", icon: "🌰" },
  "Suet": { name: "Rindertalg", icon: "🧈" },
  "Caraway Seed": { name: "Kümmel", icon: "🧂" },
  "Caraway Seeds": { name: "Kümmel", icon: "🧂" },
  "Sauerkraut": { name: "Sauerkraut", icon: "🥬" },
  "Prunes": { name: "Backpflaumen", icon: "🍑" },
  "Passata": { name: "Passierte Tomaten", icon: "🥫" },
  "Custard": { name: "Vanillesoße", icon: "🥛" },
  "Clams": { name: "Venusmuscheln", icon: "🦀" },
  "Gruyère": { name: "Gruyère", icon: "🧀" },
  "Gruyere": { name: "Gruyère", icon: "🧀" },
  "Broad Beans": { name: "Saubohnen", icon: "🫘" },
  "Digestive Biscuits": { name: "Butterkekse", icon: "🍪" },
  "digestive biscuits": { name: "Butterkekse", icon: "🍪" },
  "All-purpose Seasoning": { name: "Allzweck-Gewürzmischung", icon: "🧂" },
  "Semolina": { name: "Hartweizengrieß", icon: "🌾" },
  "Black Pudding": { name: "Blutwurst", icon: "🌭" },
  "Dried Fruit": { name: "Trockenfrüchte", icon: "🍇" },
  "Currants": { name: "Korinthen", icon: "🍇" },
  "Jam": { name: "Marmelade", icon: "🥫" },
  "Apricot Jam": { name: "Aprikosenmarmelade", icon: "🥫" },
  "Raspberry Jam": { name: "Himbeermarmelade", icon: "🥫" },
  "raspberry jam": { name: "Himbeermarmelade", icon: "🥫" },
  "Blackcurrant Jam": { name: "Schwarze Johannisbeer-Marmelade", icon: "🥫" },
  "Pretzels": { name: "Brezeln", icon: "🥨" },
  "Galangal": { name: "Galgant", icon: "🫚" },
  "Pak Choi": { name: "Pak Choi", icon: "🥬" },
  "Bok Choy": { name: "Pak Choi", icon: "🥬" },
  "Hummus": { name: "Hummus", icon: "🥫" },
  "Ground Cardomom": { name: "Kardamom", icon: "🧂" },
  "Goose Fat": { name: "Gänseschmalz", icon: "🧈" },
  "Celeriac": { name: "Knollensellerie", icon: "🥬" },
  "Sesame Seed Burger Buns": { name: "Burger-Brötchen", icon: "🍞" },
  "Burger Buns": { name: "Burger-Brötchen", icon: "🍞" },
  "Buckwheat": { name: "Buchweizen", icon: "🌾" },
  "Dark Rum": { name: "Rum", icon: "🥃" },
  "Rum": { name: "Rum", icon: "🥃" },
  "Pickle Juice": { name: "Gurkenwasser", icon: "🥒" },
  "Candied Peel": { name: "Zitronat", icon: "🍋" },
  "Glace Cherry": { name: "Belegkirsche", icon: "🍒" },
  "Glace Cherries": { name: "Belegkirsche", icon: "🍒" },
  "Grand Marnier": { name: "Grand Marnier", icon: "🍷" },
  "Mixed Peel": { name: "Zitronat", icon: "🍋" },
  "Jerusalem Artichokes": { name: "Topinambur", icon: "🥕" },
  "jamón ibérico": { name: "Jamón Ibérico", icon: "🥓" },
  "Miniature Marshmallows": { name: "Mini-Marshmallows", icon: "🍬" },
  "Marshmallows": { name: "Marshmallows", icon: "🍬" },
  "Goat Meat": { name: "Ziegenfleisch", icon: "🥩" },
  "Dried cranberries": { name: "Cranberries (getrocknet)", icon: "🫐" },
  "Cranberries": { name: "Cranberries", icon: "🫐" },
  "Mincemeat": { name: "Mincemeat", icon: "🥫" },
  "Roasted Peanut": { name: "Erdnüsse (geröstet)", icon: "🥜" },
  "Roasted Peanuts": { name: "Erdnüsse (geröstet)", icon: "🥜" },
  "Frozen Seafood mix": { name: "Meeresfrüchte-Mix", icon: "🦐" },
  "Meringue Nests": { name: "Baiser", icon: "🧁" },
  "Turkish Delight": { name: "Lokum", icon: "🍬" },
  "Shredded Meat": { name: "Fleisch (zerzupft)", icon: "🥩" },
  "Morcilla": { name: "Blutwurst", icon: "🌭" },
  "barramundi": { name: "Barramundi", icon: "🐟" },
  "Pink Food Colouring": { name: "Lebensmittelfarbe", icon: "🎨" },
  "Food Colouring": { name: "Lebensmittelfarbe", icon: "🎨" },
  "Food Coloring": { name: "Lebensmittelfarbe", icon: "🎨" },
  "Marzipan": { name: "Marzipan", icon: "🧁" },
  "Stout": { name: "Stout-Bier", icon: "🍺" },
  "Oysters": { name: "Austern", icon: "🦪" },
  "Bouquet Garni": { name: "Kräutersträußchen", icon: "🌿" },
  "Frozen Mixed Berries": { name: "Beeren-Mix (TK)", icon: "🫐" },
  "Mixed Berries": { name: "Beeren-Mix", icon: "🫐" },
  "Kielbasa": { name: "Kielbasa-Wurst", icon: "🌭" },
  "Juniper Berries": { name: "Wacholderbeeren", icon: "🫐" },

  // ── Round 3: After removing substring-fuzzy ──
  "Sesame Seed Oil": { name: "Sesamöl", icon: "🫗" },
  "Sesame Seed": { name: "Sesam", icon: "🌰" },
  "Sesame Oil": { name: "Sesamöl", icon: "🫗" },
  "Corn Flour": { name: "Speisestärke", icon: "🌾" },
  "Maize Flour": { name: "Maismehl", icon: "🌾" },
  "Muscovado Sugar": { name: "Muscovado-Zucker", icon: "🧂" },
  "Basil Leaves": { name: "Basilikum", icon: "🌿" },
  "Pita Bread": { name: "Pita-Brot", icon: "🫓" },
  "Pita": { name: "Pita-Brot", icon: "🫓" },
  "Kosher Salt": { name: "Salz", icon: "🧂" },
  "Flaky Sea Salt": { name: "Salz", icon: "🧂" },
  "Clear Honey": { name: "Honig", icon: "🍯" },
  "Runny Honey": { name: "Honig", icon: "🍯" },
  "Hotsauce": { name: "Tabasco", icon: "🌶️" },
  "Egg Plants": { name: "Aubergine", icon: "🍆" },
  "Egg Plant": { name: "Aubergine", icon: "🍆" },
  "White Cabbage": { name: "Weißkohl", icon: "🥬" },
  "Green Cabbage": { name: "Weißkohl", icon: "🥬" },
  "Dry White Wine": { name: "Weißwein", icon: "🍷" },
  "Dry Red Wine": { name: "Rotwein", icon: "🍷" },
  "Thai Red Curry Paste": { name: "Currypaste", icon: "🥫" },
  "Thai Green Curry Paste": { name: "Currypaste", icon: "🥫" },
  "Red Curry Paste": { name: "Currypaste", icon: "🥫" },
  "Green Curry Paste": { name: "Currypaste", icon: "🥫" },
  "Melted Butter": { name: "Butter", icon: "🧈" },
  "Softened Butter": { name: "Butter", icon: "🧈" },
  "Orange Blossom Water": { name: "Orangenblütenwasser", icon: "💧" },
  "Rose Water": { name: "Rosenwasser", icon: "💧" },
  "Coriander Leaves": { name: "Koriander", icon: "🌿" },
  "Coriander Seeds": { name: "Koriandersamen", icon: "🧂" },
  "Ground Coriander": { name: "Koriander (gemahlen)", icon: "🧂" },
  "Tomato Sauce": { name: "Tomatensauce", icon: "🥫" },
  "Jasmine Rice": { name: "Jasminreis", icon: "🍚" },
  "Brown Rice": { name: "Naturreis", icon: "🍚" },
  "Wild Rice": { name: "Wildreis", icon: "🍚" },
  "Sushi Rice": { name: "Sushireis", icon: "🍚" },
  "Golden Caster Sugar": { name: "Zucker", icon: "🧂" },
  "Sirloin Steak": { name: "Roastbeef", icon: "🥩" },
  "Sirloin steak": { name: "Roastbeef", icon: "🥩" },
  "Rib Eye": { name: "Rib-Eye-Steak", icon: "🥩" },
  "Ribeye": { name: "Rib-Eye-Steak", icon: "🥩" },
  "Green Olives": { name: "Oliven", icon: "🫒" },
  "Sherry Vinegar": { name: "Sherry-Essig", icon: "🫗" },
  "Sherry vinegar": { name: "Sherry-Essig", icon: "🫗" },
  "Fish Stock": { name: "Brühe (Fisch)", icon: "🍲" },
  "Desiccated Coconut": { name: "Kokosraspeln", icon: "🥥" },
  "Coconut Flakes": { name: "Kokosraspeln", icon: "🥥" },
  "Chilli Flakes": { name: "Chiliflocken", icon: "🌶️" },
  "Chili Flakes": { name: "Chiliflocken", icon: "🌶️" },
  "Red Pepper Flakes": { name: "Chiliflocken", icon: "🌶️" },
  "Paella Rice": { name: "Paella-Reis", icon: "🍚" },
  "Starch": { name: "Speisestärke", icon: "🌾" },
  "Birds-eye Chillies": { name: "Bird's-Eye-Chili", icon: "🌶️" },
  "Bird Eye Chillies": { name: "Bird's-Eye-Chili", icon: "🌶️" },
  "Strong White Bread Flour": { name: "Brotmehl", icon: "🌾" },
  "Strong white bread flour": { name: "Brotmehl", icon: "🌾" },
  "Lemongrass Stalks": { name: "Zitronengras", icon: "🌿" },
  "Lemongrass": { name: "Zitronengras", icon: "🌿" },
  "Lemon Grass": { name: "Zitronengras", icon: "🌿" },

  // Common variants picked up from later runs
  "Cilantro Leaves": { name: "Koriander", icon: "🌿" },
  "Mint Leaves": { name: "Minze", icon: "🍃" },
  "Bay Leafs": { name: "Lorbeerblatt", icon: "🍃" },
  "Frozen Mixed Vegetables": { name: "Gemüse-Mix (TK)", icon: "🥦" },
  "Mixed Vegetables": { name: "Gemüse-Mix", icon: "🥦" },
  "Frozen Spinach": { name: "Spinat", icon: "🥬" },
  "Baby Spinach": { name: "Spinat", icon: "🥬" },
  "Tomato Soup": { name: "Tomatensuppe", icon: "🍲" },
  "Tomato Pasata": { name: "Passierte Tomaten", icon: "🥫" },
  "Salt And Pepper": { name: "Salz und Pfeffer", icon: "🧂" },
  "Black Beans": { name: "Schwarze Bohnen", icon: "🫘" },
  "Pinto Beans": { name: "Pintobohnen", icon: "🫘" },
  "Refried Beans": { name: "Refried Beans", icon: "🫘" },
  "Egg Roll Wrappers": { name: "Eierteigblätter", icon: "🥟" },
  "Wonton Wrappers": { name: "Wantanblätter", icon: "🥟" },
  "Wonton-Blätter": { name: "Wantanblätter", icon: "🥟" },
  "Phyllo Dough": { name: "Filoteig", icon: "🥐" },
  "Phyllo Pastry": { name: "Filoteig", icon: "🥐" },
  "Filo": { name: "Filoteig", icon: "🥐" },
  "Cooking Spray": { name: "Sprühfett", icon: "🫗" },
  "Lemon Rind": { name: "Zitronenschale", icon: "🍋" },
  "Lemon Peel": { name: "Zitronenschale", icon: "🍋" },
  "Orange Zest": { name: "Orangenschale", icon: "🍊" },
  "Orange Rind": { name: "Orangenschale", icon: "🍊" },
  "Mascarpone Cheese": { name: "Mascarpone", icon: "🧀" },
  "Ricotta Cheese": { name: "Ricotta", icon: "🧀" },
  "Mozzarella Balls": { name: "Mozzarella", icon: "🧀" },
  "Buffalo Mozzarella": { name: "Mozzarella", icon: "🧀" },
  "Vanilla Pods": { name: "Vanille", icon: "🌰" },
  "Vanilla Sugar": { name: "Vanillezucker", icon: "🧁" },

  // ── Round 4 ──
  "Ground Nut Oil": { name: "Erdnussöl", icon: "🫗" },
  "Peanut Oil": { name: "Erdnussöl", icon: "🫗" },
  "Black Treacle": { name: "Melasse", icon: "🍯" },
  "Treacle": { name: "Melasse", icon: "🍯" },
  "Beef Fillet": { name: "Rinderfilet", icon: "🥩" },
  "Beef Shin": { name: "Rinderhaxe", icon: "🥩" },
  "Beef Cheeks": { name: "Rinderbäckchen", icon: "🥩" },
  "Crusty Bread": { name: "Brot", icon: "🍞" },
  "White Vinegar": { name: "Essig", icon: "🫗" },
  "Distilled Vinegar": { name: "Essig", icon: "🫗" },
  "Shiitake Mushrooms": { name: "Shiitake-Pilze", icon: "🍄" },
  "Brown Lentils": { name: "Linsen (braun)", icon: "🫘" },
  "Tiger Prawns": { name: "Garnelen", icon: "🦐" },
  "Braeburn Apples": { name: "Apfel", icon: "🍎" },
  "Granny Smith Apples": { name: "Apfel", icon: "🍎" },
  "Apricot": { name: "Aprikose", icon: "🍑" },
  "Goats Cheese": { name: "Ziegenkäse", icon: "🧀" },
  "Goat's Cheese": { name: "Ziegenkäse", icon: "🧀" },
  "Chimichurri sauce": { name: "Chimichurri", icon: "🥫" },
  "Chimichurri": { name: "Chimichurri", icon: "🥫" },
  "Salt Cod": { name: "Stockfisch", icon: "🐟" },
  "Celery Salt": { name: "Selleriesalz", icon: "🧂" },
  "Light Brown Soft Sugar": { name: "Brauner Zucker", icon: "🧂" },
  "Soft Brown Sugar": { name: "Brauner Zucker", icon: "🧂" },
  "Ground Clove": { name: "Nelken", icon: "🧂" },
  "Ground Cloves": { name: "Nelken", icon: "🧂" },
  "Russet Potato": { name: "Kartoffel", icon: "🥔" },
  "Russet Potatoes": { name: "Kartoffel", icon: "🥔" },
  "New Potatoes": { name: "Frühkartoffeln", icon: "🥔" },
  "Baby New Potatoes": { name: "Frühkartoffeln", icon: "🥔" },
  "Jersey Royal Potatoes": { name: "Frühkartoffeln", icon: "🥔" },
  "Water Chestnut": { name: "Wasserkastanien", icon: "🌰" },
  "Water Chestnuts": { name: "Wasserkastanien", icon: "🌰" },
  "Cider Vinegar": { name: "Apfelessig", icon: "🫗" },
  "Sage": { name: "Salbei", icon: "🌿" },
  "Fresh Sage": { name: "Salbei", icon: "🌿" },
  "makrut lime leaves": { name: "Kaffirlimettenblätter", icon: "🍃" },
  "Lime Leaves": { name: "Kaffirlimettenblätter", icon: "🍃" },
  "Kaffir Lime Leaves": { name: "Kaffirlimettenblätter", icon: "🍃" },
  "Duck Sauce": { name: "Pflaumensauce", icon: "🥫" },
  "Ice Cream": { name: "Eiscreme", icon: "🍦" },
  "Vanilla Ice Cream": { name: "Vanilleeis", icon: "🍦" },
  "Naan Bread": { name: "Naan", icon: "🫓" },
  "Naan": { name: "Naan", icon: "🫓" },
  "Barbeque Sauce": { name: "BBQ-Sauce", icon: "🥫" },
  "Bbq Sauce": { name: "BBQ-Sauce", icon: "🥫" },
};

// Strip qualifier words for fuzzy matching: "Extra Virgin Olive Oil" → "Olive Oil"
const QUALIFIERS = new Set([
  "extra", "virgin", "fresh", "frozen", "dried", "ground", "whole", "raw",
  "cooked", "boneless", "skinless", "lean", "minced", "chopped", "sliced",
  "diced", "shredded", "grated", "peeled", "small", "large", "medium",
  "baby", "young", "wild", "organic", "free-range", "free", "range",
  "smoked", "cured", "salted", "unsalted", "sweet", "sour", "bitter",
  "thinly", "finely", "roughly", "lightly", "tinned", "canned", "jarred",
  "plain", "natural", "creamed", "active", "instant", "self-raising",
  "self", "raising", "all-purpose", "purpose", "warm", "hot", "cold",
  "premium", "quality", "strong", "mild", "tender",
]);

function normalizeName(name) {
  return name
    .toLowerCase()
    .replace(/[^\w\s]/g, " ")
    .split(/\s+/)
    .filter((w) => w && !QUALIFIERS.has(w))
    .join(" ")
    .trim();
}

const DEFAULT_ICON = "⭐";

// Stats collected during run
export const stats = {
  exact: 0,
  fuzzy: 0,
  auto: 0,
  unmatched: {}, // name → count
};

/**
 * @returns { name: string, icon: string }
 */
export function matchIngredient(rawName) {
  if (!rawName) return null;
  const trimmed = rawName.trim();
  if (!trimmed) return null;

  // Stage 1: exact lookup
  if (INGREDIENT_MAP[trimmed]) {
    stats.exact++;
    return INGREDIENT_MAP[trimmed];
  }

  // Try case-insensitive exact
  const lowerKey = trimmed.toLowerCase();
  for (const k of Object.keys(INGREDIENT_MAP)) {
    if (k.toLowerCase() === lowerKey) {
      stats.exact++;
      return INGREDIENT_MAP[k];
    }
  }

  // Stage 2: fuzzy via normalization (qualifier-stripping)
  // Only EXACT match after normalization — no substring fuzzy (too risky:
  // "Red Pepper Paste" must NOT match "Red Pepper").
  const normalizedInput = normalizeName(trimmed);
  if (normalizedInput) {
    for (const [key, val] of Object.entries(INGREDIENT_MAP)) {
      if (normalizeName(key) === normalizedInput) {
        stats.fuzzy++;
        return val;
      }
    }
  }

  // Stage 3: auto-create as custom ingredient
  stats.auto++;
  stats.unmatched[trimmed] = (stats.unmatched[trimmed] || 0) + 1;
  return { name: trimmed, icon: DEFAULT_ICON };
}

export function resetStats() {
  stats.exact = 0;
  stats.fuzzy = 0;
  stats.auto = 0;
  stats.unmatched = {};
}
