// Conversion factors to SI base units (g for mass, ml for volume)
// Source: standard cooking conversions

export const UNIT_CONVERSIONS = {
  // Mass → g
  g:          { unit: "g",  factor: 1 },
  gram:       { unit: "g",  factor: 1 },
  grams:      { unit: "g",  factor: 1 },
  kg:         { unit: "kg", factor: 1 },
  kilo:       { unit: "kg", factor: 1 },
  kilogram:   { unit: "kg", factor: 1 },
  kilograms:  { unit: "kg", factor: 1 },
  oz:         { unit: "g",  factor: 28.35 },
  ounce:      { unit: "g",  factor: 28.35 },
  ounces:     { unit: "g",  factor: 28.35 },
  lb:         { unit: "g",  factor: 453.6 },
  lbs:        { unit: "g",  factor: 453.6 },
  pound:      { unit: "g",  factor: 453.6 },
  pounds:     { unit: "g",  factor: 453.6 },

  // Volume → ml
  ml:          { unit: "ml", factor: 1 },
  milliliter:  { unit: "ml", factor: 1 },
  milliliters: { unit: "ml", factor: 1 },
  l:           { unit: "l",  factor: 1 },
  liter:       { unit: "l",  factor: 1 },
  liters:      { unit: "l",  factor: 1 },
  litre:       { unit: "l",  factor: 1 },
  litres:      { unit: "l",  factor: 1 },
  tsp:         { unit: "ml", factor: 5 },
  teaspoon:    { unit: "ml", factor: 5 },
  teaspoons:   { unit: "ml", factor: 5 },
  tbs:         { unit: "ml", factor: 15 },
  tbsp:        { unit: "ml", factor: 15 },
  tbsps:       { unit: "ml", factor: 15 },
  tblsp:       { unit: "ml", factor: 15 },
  tablespoon:  { unit: "ml", factor: 15 },
  tablespoons: { unit: "ml", factor: 15 },
  cup:         { unit: "ml", factor: 240 },
  cups:        { unit: "ml", factor: 240 },
  pint:        { unit: "ml", factor: 473 },
  pints:       { unit: "ml", factor: 473 },
  pt:          { unit: "ml", factor: 473 },
  quart:       { unit: "l",  factor: 0.946 },
  quarts:      { unit: "l",  factor: 0.946 },
  qt:          { unit: "l",  factor: 0.946 },
  qts:         { unit: "l",  factor: 0.946 },
  gallon:      { unit: "l",  factor: 3.785 },
  gallons:     { unit: "l",  factor: 3.785 },
  gal:         { unit: "l",  factor: 3.785 },
  "fl oz":     { unit: "ml", factor: 29.57 },
  "fl. oz":    { unit: "ml", factor: 29.57 },

  // Count → stk
  clove:    { unit: "stk", factor: 1 },
  cloves:   { unit: "stk", factor: 1 },
  bulb:     { unit: "stk", factor: 1 },
  bulbs:    { unit: "stk", factor: 1 },
  head:     { unit: "stk", factor: 1 },
  heads:    { unit: "stk", factor: 1 },
  slice:    { unit: "stk", factor: 1 },
  slices:   { unit: "stk", factor: 1 },
  stick:    { unit: "stk", factor: 1 },
  sticks:   { unit: "stk", factor: 1 },
  can:      { unit: "stk", factor: 1 },
  cans:     { unit: "stk", factor: 1 },
  tin:      { unit: "stk", factor: 1 },
  tins:     { unit: "stk", factor: 1 },
  jar:      { unit: "stk", factor: 1 },
  jars:     { unit: "stk", factor: 1 },
  packet:   { unit: "stk", factor: 1 },
  packets:  { unit: "stk", factor: 1 },
  package:  { unit: "stk", factor: 1 },
  pack:     { unit: "stk", factor: 1 },
  bag:      { unit: "stk", factor: 1 },
  bunch:    { unit: "stk", factor: 1 },
  bunches:  { unit: "stk", factor: 1 },
  sprig:    { unit: "stk", factor: 1 },
  sprigs:   { unit: "stk", factor: 1 },
  piece:    { unit: "stk", factor: 1 },
  pieces:   { unit: "stk", factor: 1 },
};

// Order matters: longest first to avoid partial matches
export const UNIT_KEYS_ORDERED = Object.keys(UNIT_CONVERSIONS).sort(
  (a, b) => b.length - a.length
);
